platform :ios, '10.0'

target 'SheUp' do
use_frameworks!

pod 'YYModel'
pod 'FMDB'
pod 'SVProgressHUD'
pod 'pop', '~> 1.0'
pod 'SnapKit', '~> 4.0.0'
pod 'NVActivityIndicatorView'
pod 'Alamofire', '~> 4.5'
pod 'ImagePicker'
pod 'RAMAnimatedTabBarController'
pod 'SwiftyJSON'
pod 'ReactiveSwift', '~> 3.0'
pod 'MJRefresh'
pod 'Kingfisher','~>4.5.0'
pod 'RxSwift', '~> 4.0.0'
pod 'RxCocoa', '~> 4.0'
pod 'Action',  '~>3.5.0'
pod 'RxDataSources', '~> 3.0.2'
end
